[E 241029 00:43:21 test:674] Historic Api failed: unsupported operand type(s) for +: 'int' and 'NoneType'
    Traceback (most recent call last):
      File "D:\python project\test.py", line 67, in <module>
        C1Target = C1Value+Pvalue
                   ~~~~~~~^~~~~~~
    TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
[E 241029 00:44:09 test:674] Historic Api failed: unsupported operand type(s) for +: 'int' and 'NoneType'
    Traceback (most recent call last):
      File "D:\python project\test.py", line 67, in <module>
        C1Target = C1Value+Pvalue
                   ~~~~~~~^~~~~~~
    TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
[E 241029 00:47:33 smartConnect:246] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData. Error: Invalid date or time format. URL: https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData, Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'b0:47:e9:6c:91:c9', 'Accept': 'application/json', 'X-PrivateKey': 'RgOlMNVl', 'X-UserType': 'USER', 'X-SourceID': 'WEB'}, Request: {'exchange': 'NSE', 'interval': 'ONE_MINUTE', 'fromdate': "<Cell 'list'.A2> 09:15", 'todate': "<Cell 'list'.A2> 15:15"}, Response: {'message': 'Invalid date or time format', 'errorcode': 'AB13000', 'status': False, 'data': None}
[E 241029 00:47:33 test:674] Historic Api failed: 0
    Traceback (most recent call last):
      File "C:\Users\RAHUL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\range.py", line 413, in get_loc
        return self._range.index(new_key)
               ~~~~~~~~~~~~~~~~~^^^^^^^^^
    ValueError: 0 is not in range
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "D:\python project\test.py", line 113, in <module>
        df[0] = pd.to_datetime(df[0], format='%Y-%m-%dT%H:%M:%S%z')
                               ~~^^^
      File "C:\Users\RAHUL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
        indexer = self.columns.get_loc(key)
      File "C:\Users\RAHUL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\range.py", line 415, in get_loc
        raise KeyError(key) from err
    KeyError: 0
[E 241029 21:09:18 smartConnect:246] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData. Error: Invalid date or time format. URL: https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData, Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'b0:47:e9:6c:91:c9', 'Accept': 'application/json', 'X-PrivateKey': 'RgOlMNVl', 'X-UserType': 'USER', 'X-SourceID': 'WEB'}, Request: {'exchange': 'NSE', 'symboltoken': 7, 'interval': 'ONE_MINUTE', 'fromdate': "<Cell 'list'.A2> 09:15", 'todate': "<Cell 'list'.A2> 15:15"}, Response: {'message': 'Invalid date or time format', 'errorcode': 'AB13000', 'status': False, 'data': None}
[E 241029 21:09:18 test:674] Historic Api failed: 0
    Traceback (most recent call last):
      File "C:\Users\RAHUL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\range.py", line 413, in get_loc
        return self._range.index(new_key)
               ~~~~~~~~~~~~~~~~~^^^^^^^^^
    ValueError: 0 is not in range
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "D:\python project\test.py", line 113, in <module>
        df[0] = pd.to_datetime(df[0], format='%Y-%m-%dT%H:%M:%S%z')
                               ~~^^^
      File "C:\Users\RAHUL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
        indexer = self.columns.get_loc(key)
      File "C:\Users\RAHUL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\range.py", line 415, in get_loc
        raise KeyError(key) from err
    KeyError: 0
[E 241029 21:13:17 smartConnect:246] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData. Error: Invalid date or time format. URL: https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData, Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'b0:47:e9:6c:91:c9', 'Accept': 'application/json', 'X-PrivateKey': 'RgOlMNVl', 'X-UserType': 'USER', 'X-SourceID': 'WEB'}, Request: {'exchange': 'NSE', 'symboltoken': 7, 'interval': 'ONE_MINUTE', 'fromdate': "<Cell 'list'.A2> 09:15", 'todate': "<Cell 'list'.A2> 15:15"}, Response: {'message': 'Invalid date or time format', 'errorcode': 'AB13000', 'status': False, 'data': None}
[E 241029 21:13:17 test:676] Historic Api failed: 0
    Traceback (most recent call last):
      File "C:\Users\RAHUL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\range.py", line 413, in get_loc
        return self._range.index(new_key)
               ~~~~~~~~~~~~~~~~~^^^^^^^^^
    ValueError: 0 is not in range
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "D:\python project\test.py", line 115, in <module>
        df[0] = pd.to_datetime(df[0], format='%Y-%m-%dT%H:%M:%S%z')
                               ~~^^^
      File "C:\Users\RAHUL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
        indexer = self.columns.get_loc(key)
      File "C:\Users\RAHUL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\range.py", line 415, in get_loc
        raise KeyError(key) from err
    KeyError: 0
[E 241029 21:15:03 smartConnect:246] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData. Error: Invalid date or time format. URL: https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData, Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'b0:47:e9:6c:91:c9', 'Accept': 'application/json', 'X-PrivateKey': 'RgOlMNVl', 'X-UserType': 'USER', 'X-SourceID': 'WEB'}, Request: {'exchange': 'NSE', 'symboltoken': 7, 'interval': 'ONE_MINUTE', 'fromdate': "<Cell 'list'.A2> 09:15", 'todate': "<Cell 'list'.A2> 15:15"}, Response: {'message': 'Invalid date or time format', 'errorcode': 'AB13000', 'status': False, 'data': None}
[E 241029 21:15:04 smartConnect:246] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData. Error: Invalid date or time format. URL: https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData, Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'b0:47:e9:6c:91:c9', 'Accept': 'application/json', 'X-PrivateKey': 'RgOlMNVl', 'X-UserType': 'USER', 'X-SourceID': 'WEB'}, Request: {'exchange': 'NSE', 'symboltoken': 13, 'interval': 'ONE_MINUTE', 'fromdate': "<Cell 'list'.A3> 09:15", 'todate': "<Cell 'list'.A3> 15:15"}, Response: {'message': 'Invalid date or time format', 'errorcode': 'AB13000', 'status': False, 'data': None}
[E 241029 21:15:05 smartConnect:246] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData. Error: Invalid date or time format. URL: https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData, Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'b0:47:e9:6c:91:c9', 'Accept': 'application/json', 'X-PrivateKey': 'RgOlMNVl', 'X-UserType': 'USER', 'X-SourceID': 'WEB'}, Request: {'exchange': 'NSE', 'symboltoken': 17903, 'interval': 'ONE_MINUTE', 'fromdate': "<Cell 'list'.A4> 09:15", 'todate': "<Cell 'list'.A4> 15:15"}, Response: {'message': 'Invalid date or time format', 'errorcode': 'AB13000', 'status': False, 'data': None}
[E 241029 21:15:06 smartConnect:246] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData. Error: Invalid date or time format. URL: https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData, Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'b0:47:e9:6c:91:c9', 'Accept': 'application/json', 'X-PrivateKey': 'RgOlMNVl', 'X-UserType': 'USER', 'X-SourceID': 'WEB'}, Request: {'exchange': 'NSE', 'symboltoken': 21614, 'interval': 'ONE_MINUTE', 'fromdate': "<Cell 'list'.A5> 09:15", 'todate': "<Cell 'list'.A5> 15:15"}, Response: {'message': 'Invalid date or time format', 'errorcode': 'AB13000', 'status': False, 'data': None}
[E 241029 21:15:08 smartConnect:246] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData. Error: Invalid date or time format. URL: https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData, Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'b0:47:e9:6c:91:c9', 'Accept': 'application/json', 'X-PrivateKey': 'RgOlMNVl', 'X-UserType': 'USER', 'X-SourceID': 'WEB'}, Request: {'exchange': 'NSE', 'symboltoken': 30108, 'interval': 'ONE_MINUTE', 'fromdate': "<Cell 'list'.A6> 09:15", 'todate': "<Cell 'list'.A6> 15:15"}, Response: {'message': 'Invalid date or time format', 'errorcode': 'AB13000', 'status': False, 'data': None}
[E 241029 21:15:09 smartConnect:246] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData. Error: Invalid date or time format. URL: https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData, Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'b0:47:e9:6c:91:c9', 'Accept': 'application/json', 'X-PrivateKey': 'RgOlMNVl', 'X-UserType': 'USER', 'X-SourceID': 'WEB'}, Request: {'exchange': 'NSE', 'symboltoken': 22, 'interval': 'ONE_MINUTE', 'fromdate': "<Cell 'list'.A7> 09:15", 'todate': "<Cell 'list'.A7> 15:15"}, Response: {'message': 'Invalid date or time format', 'errorcode': 'AB13000', 'status': False, 'data': None}
[E 241029 21:15:10 smartConnect:246] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData. Error: Invalid date or time format. URL: https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData, Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'b0:47:e9:6c:91:c9', 'Accept': 'application/json', 'X-PrivateKey': 'RgOlMNVl', 'X-UserType': 'USER', 'X-SourceID': 'WEB'}, Request: {'exchange': 'NSE', 'symboltoken': 25, 'interval': 'ONE_MINUTE', 'fromdate': "<Cell 'list'.A8> 09:15", 'todate': "<Cell 'list'.A8> 15:15"}, Response: {'message': 'Invalid date or time format', 'errorcode': 'AB13000', 'status': False, 'data': None}
[E 241029 21:15:11 smartConnect:246] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData. Error: Invalid date or time format. URL: https://apiconnect.angelone.in/rest/secure/angelbroking/historical/v1/getCandleData, Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'b0:47:e9:6c:91:c9', 'Accept': 'application/json', 'X-PrivateKey': 'RgOlMNVl', 'X-UserType': 'USER', 'X-SourceID': 'WEB'}, Request: {'exchange': 'NSE', 'symboltoken': 15083, 'interval': 'ONE_MINUTE', 'fromdate': "<Cell 'list'.A9> 09:15", 'todate': "<Cell 'list'.A9> 15:15"}, Response: {'message': 'Invalid date or time format', 'errorcode': 'AB13000', 'status': False, 'data': None}
